apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: argocd-alerts
  namespace: monitoring
  labels:
    app.kubernetes.io/name: argocd-alerts
    release: kube-prometheus-stack
spec:
  groups:
    - name: argocd.rules
      rules:
        - alert: ArgoAppNotSynced
          expr: argocd_app_info{sync_status!="Synced"}
          for: 5m
          labels:
            severity: critical
            component: argocd-app
            team: gitops
          annotations:
            summary: "Application ArgoCD non synchronisée"
            description: "L'application {{ $labels.name }} n'est pas synchronisée depuis 5 minutes."

        - alert: ArgoAppUnhealthy
          expr: argocd_app_info{health_status!="Healthy"}
          for: 5m
          labels:
            severity: critical
            component: argocd-app
            team: gitops
          annotations:
            summary: "Application ArgoCD en mauvaise santé"
            description: "L'application {{ $labels.name }} n'est pas saine depuis 5 minutes."