prometheus:
  prometheusSpec:
    retention: 15d
    scrapeInterval: 30s
    evaluationInterval: 30s

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
    resources:
      requests:
        memory: 2Gi
        cpu: 1
      limits:
        memory: 4Gi
        cpu: 2

    serviceMonitorSelectorNilUsesHelmValues: true
    serviceMonitorSelector: {}
    ruleSelector: {}
    ruleSelectorNilUsesHelmValues: false

    additionalScrapeConfigs:
      - job_name: 'argocd-metrics'
        static_configs:
          - targets: ['argocd-application-controller-metrics.argocd.svc.cluster.local:8082']
      - job_name: 'argocd-server-metrics'
        static_configs:
          - targets: ['argocd-repo-server-metrics.argocd.svc.cluster.local:8084']
      - job_name: 'ecommerce-app'
        static_configs:
          - targets: ['ecommerce-service.ecommerce.svc.cluster.local:8080'] 
        metrics_path: /metrics
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            regex: '([^:]+)(:\d+)?'
            replacement: $1

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi

grafana:
  enabled: false

kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false

nodeExporter:
  enabled: true
kube-state-metrics:
  enabled: true

prometheus-operator:
  prometheus-rules:
    enabled: true
    rules:
      falco-critical-alerts:
        alert: FalcoHighCriticalAlertRate
        expr: |
          sum(rate(falco_alerts{priority="Critical"}[5m])) > 5
        for: 5m
        labels:
          severity: critical
          team: security
        annotations:
          summary: "High number of falco alerts detected"
          description: "The number of 'Critical' alerts is more than 5/minute for more than 5 minutes. Please check the Loki logs and Falco metrics."