apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  source:
    - repoURL: https://falcosecurity.github.io/charts
      chart: falco
      targetRevision: 3.7.3 
      helm:
        values:
          driver:
            kind: ebpf

        falco:
          rules_files:
            - /etc/falco/falco_rules.yaml
            - /etc/falco/falco_rules.local.yaml
            - /etc/falco/rules.d

          json_output: true
          json_include_output_property: true
              
          webserver:
            enabled: true
            k8s_healthz_endpoint: /healthz
            
            # ServiceMonitor pour Prometheus
        serviceMonitor:
          enabled: true

    - repoURL: https://github.com/votre-username/votre-repo.git
      targetRevision: HEAD
      path: security/falco
      directory:
        recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: falco

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m