apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security-falco
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: security-falco
    app.kubernetes.io/component: security
spec:
  project: default
  
  sources:
    # Chart Helm Falco
    - repoURL: https://falcosecurity.github.io/charts
      chart: falco
      targetRevision: 3.8.4
      helm:
        releaseName: falco
        valueFiles:
          - $values/security/falco/values.yaml
    
    # Values depuis Git
    - repoURL: https://github.com/Titou-Onee/CloudDevOps_ecommerce.git
      targetRevision: HEAD
      ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m