# CloudFormation Template for S3 backend
# aws cloudformation deploy --template-file .\s3_backend.yml --stack-name devsecops --parameter-overrides GitHubRepoName=Titou-Onee/CloudDevOps_ecommerce TerraformStateBucketName=remotestate18569402 --capabilities CAPABILITY_NAMED_IAM
AWSTemplateFormatVersion: "2010-09-09"
Description: Terraform Backend and GitHub OIDC

Parameters:
  TerraformStateBucketName:
    Type: String
    Description: Name of the S3 bucket used for Terraform state

  GitHubRepoName:
    Type: String
    Description: GitHub repository in the format owner/repo

Resources:
  TerraformStateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref TerraformStateBucketName
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  TerraformStateBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TerraformStateBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !GetAtt GitHubActionsRole.Arn
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
            Resource:
              - !Sub "${TerraformStateBucket.Arn}"
              - !Sub "${TerraformStateBucket.Arn}/*"

  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1

  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GitHubActionsTerraformRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubOIDCProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub "repo:${GitHubRepoName}:*"

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

Outputs:
  TerraformStateBucketName:
    Value: !Ref TerraformStateBucket

  GitHubActionsRoleArn:
    Value: !GetAtt GitHubActionsRole.Arn