apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8saccesspolicy
metadata:
  name: access-policy
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  enforcementAction : dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["rbac.authorization.k8s.io"]
        kinds: ["Role"]
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
    excludedNamespaces:
      - kube-system
   #   - security
#templates : nom en minuscules et kin en majuscule, faire pareil pour les constraints