apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sNamespacePolicy
metadata:
  name: namespace-policy
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  enforcementAction : dryrun
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
    excludedNamespaces:
      - kube-system
      - argocd
