# Application of the LabelDeployment
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8sLabelDeployment
metadata:
  name: label-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  enforcementAction : warn
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
    excludedNamespaces:
      - kube-system
      - argocd
      - security
      - monitoring
      - ingress-nginx
