apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: gatekeeper-system
spec:
  sync:
    syncOnly:
      # 1. RBAC
      - group: "rbac.authorization.k8s.io"
        version: "v1"
        kind: "Role"
      - group: "rbac.authorization.k8s.io"
        version: "v1"
        kind: "ClusterRole"
      
      # 2. Network Objects
      - group: "networking.k8s.io"
        version: "v1"
        kind: "Ingress"
        
      # 3.GitOps Object
      - group: "argoproj.io"
        version: "v1alpha1"
        kind: "Application"
        
      # Core Resources
      - group: ""
        version: "v1"
        kind: "Pod"
      - group: ""
        version: "v1"
        kind: "Service"
      - group: ""
        version: "v1"
        kind: "ConfigMap"
      - group: ""
        version: "v1"
        kind: "Secret"
      - group: ""
        version: "v1"
        kind: "PersistentVolumeClaim"
      - group: "storage.k8s.io"
        version: "v1"
        kind: "StorageClass"
      
      # Apps Workloads
      - group: "apps"
        version: "v1"
        kind: "Deployment"
      - group: "apps"
        version: "v1"
        kind: "StatefulSet"
      - group: "apps"
        version: "v1"
        kind: "DaemonSet"
        
      # Batch Jobs
      - group: "batch"
        version: "v1"
        kind: "Job"
      - group: "batch"
        version: "v1"
        kind: "CronJob"