apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: gatekeeper-system
spec:
  sync:
    syncOnly:
      # Core Resources (used in your constraints)
      - group: ""
        version: "v1"
        kind: "Pod"
      - group: ""
        version: "v1"
        kind: "Service"
      - group: ""
        version: "v1"
        kind: "ConfigMap"
      - group: ""
        version: "v1"
        kind: "Secret"
      - group: ""
        version: "v1"
        kind: "PersistentVolumeClaim"
      - group: "storage.k8s.io"
        version: "v1"
        kind: "StorageClass"
      - group: ""
        version: "v1"
        kind: "PersistentVolume"
      # Apps Workloads
      - group: "apps"
        version: "v1"
        kind: "Deployment"
      - group: "apps"
        version: "v1"
        kind: "StatefulSet"
      - group: "apps"
        version: "v1"
        kind: "DaemonSet"
      - group: "apps"
        version: "v1"
        kind: "ReplicaSet"
      
      # Batch Jobs
      - group: "batch"
        version: "v1"
        kind: "Job"
      - group: "batch"
        version: "v1"
        kind: "CronJob"