# template for use of non-certified registry
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8simagepolicy
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  crd:
    spec:
      names:
        kind: K8sImagePolicy
      validation:
        openAPIV3Schema:
          type: object
          properties:
            approvedRegistry:
              type: array
              description: "List of authorized registries"
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8simagepolicy
        
        all_containers[container] {
            some c
            container := input.review.object.spec.containers[c]
        }
        all_containers[container] {
            input.review.object.spec.initContainers
            some c
            container := input.review.object.spec.initContainers[c]
        }
        all_containers[container] {
            input.review.object.spec.ephemeralContainers
            some c
            container := input.review.object.spec.ephemeralContainers[c]
        }
        default msg = ""

        is_approved(image, approved) {
        startswith(image, approved)
        }

        violation[{"msg": msg}] {
            # L'opérateur [_] est utilisé pour itérer sur les éléments d'un ensemble.
            container := all_containers[_]
            approved := input.parameters.approvedRegistry
            
            # Vérification
            not is_approved(container.image, approved)

            msg := sprintf("The image %q doesn't come from an approved registry", [container.image])
        }


