apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security-falco
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: security-falco
    app.kubernetes.io/component: security
spec:
  project: security-project
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /metadata
        - /status 
  
  sources:
    - repoURL: https://falcosecurity.github.io/charts
      chart: falco
      targetRevision: 6.0.0
      helm:
        releaseName: falco
        valueFiles:
          - $values/gitops/values/values-falco.yml
    
    - repoURL: https://github.com/Titou-Onee/CloudDevOps_ecommerce.git
      targetRevision: master
      ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

        #ajouter falco sidekick