apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security-gatekeeper
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: security-gatekeeper
    app.kubernetes.io/component: security
spec:
  project: security-project
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /metadata
        - /status 
  
  source:   
    repoURL: https://github.com/Titou-Onee/CloudDevOps_ecommerce.git
    targetRevision: HEAD
    ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

# metrics dans prometheus
# ajouter ignoreDifferences
