apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
spec:
  project: default

  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 7.3.0
      helm:
        valueFiles:
          - $values/gitops/values/values-grafana.yml
   
    - repoURL: https://github.com/Titou-Onee/CloudDevOps_ecommerce.git
      targetRevision: master
      ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring


  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m


datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        isDefault: true
# ajouter l'accès 
#adminUser: admin
#adminPassword: changeme
#service:
#  type: LoadBalancer
