apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Nom de l'application Argo CD
  name: ingress-nginx-controller
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: ingress-nginx
  
  # Configuration de la source (le Chart Helm)
  sources:

    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: "4.10.1"
    
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/gitops/values/values-nginx.yml
  
    - repoURL: https://github.com/Titou-Onee/CloudDevOps_ecommerce.git
      targetRevision: master
      ref: values

            
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true