- name: Deploy argocd prometheus and grafana
  hosts: kubernetes
  gather_facts: false
 
  pre_tasks:
    - name:  Verify cluster connection
      kubernetes.core.k8s_info:
        apiVersion: v1
        kind: Node
        kubeconfig: "{{ kubeconfig_path }}"
      register: nodes
  
    - name: Display cluster informations
      debug:
      msg: "Connected to cluster with {{ nodes.ressources | length }} nodes"

  tasks:
    - name: Install argocd
      include_role:
        name: argocd
      tags: [argocd]

    - name: Install prometheus
      include_role:
        name: prometheus
      tags: [prometheus, monitoring]

    - name: Install grafana
      include_role:
        name: grafana
      tags: [grafana, monitoring]

  post_tasks:
    - name: Print access informations
      debug:
      msg: 
          - "ArgoCD"
          - "  Namespace: {{ argocd.namespace }}"
          - "  Username: admin"
          - "  Password: {{ argocd.admin_password }}"
          - "  Port-forward: kubectl port-forward svc/argocd-server -n {{ argocd.namespace }} 8080:443"
          - "  URL: https://localhost:8080"
          - ""
          - "Grafana"
          - "  Namespace: {{ grafana.namespace }}"
          - "  Username: {{ grafana.admin_user }}"
          - "  Password: {{ grafana.admin_password }}"
          - "  Port-forward: kubectl port-forward svc/grafana -n {{ grafana.namespace }} 3000:80"
          - "  URL: http://localhost:3000"
          - ""
          - "Prometheus"
          - "  Namespace: {{ prometheus.namespace }}"
          - "  Port-forward: kubectl port-forward svc/kube-prometheus-stack-prometheus -n {{ prometheus.namespace }} 9090:9090"
          - "  URL: http://localhost:9090"

    
