falco:
  jsonOutput: true
  logLevel: info

  config:
    enabled_event_sources:
      - syscall
      - k8s_audit

  rulesFile:
    - /etc/falco/falco_rules.yaml
    - /etc/falco/falco_rules.local.yaml
    - /etc/falco/rules.d

driver:
  enabled: true
  kind: modern_ebpf
  
customRules:
  custom-sec-rules.yaml: |
    - rule: Suspicious File Created in /etc
      desc: Detects file creation in /etc
      condition: evt.type = creat and fd.name startswith /etc
      output: >
        File created in /etc (user=%user.name file=%fd.name command=%proc.cmdline)
      priority: WARNING
      tags: [filesystem, etc]
