apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app
  namespace: ecommerce
  labels:
    app: ecommerce-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-app
  template:
    metadata:
      labels:
        app: ecommerce-app
    spec:
      initContainers:
        - name: postgres-migration
          image: titouonee/clouddevops_ecommerce:latest
          command: ['python3', 'manage.py', 'migrate']
          envFrom:
            - configMapRef:
                name: ecommerce-config
            - secretRef:
                name: ecommerce-secret
      containers:
      - name: ecommerce-app
        image: titouonee/clouddevops_ecommerce:latest
        command: ['python3', 'manage.py', 'runserver', '0.0.0.0:8000']
        ports:
        - containerPort: 8000
          name: http
        envFrom:
          - configMapRef:
              name: ecommerce-config
          - secretRef:
              name: ecommerce-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi" 
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
  namespace: ecommerce
  labels:
    app: ecommerce-app
spec:
  selector:
    app: ecommerce-app
  ports:
  - name: ecommerce-port
    protocol: TCP 
    port: 80
    targetPort: 8000
  type: LoadBalancer