apiVersion: apps/v1
kind: deployment
metadata:
  name: ecommerce-app
  namespace: ecommerce
  labels:
    app: ecommerce-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-app
  template:
    metadata:
      labels:
        app: ecommerce-app
    specs:
      containers:
      - name: ecommerce-app
        image: titouonee/clouddevops_ecommerce
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "false"
        - name: ALLOWED_HOSTS
          value: "*"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"