name: CI Workflow
on:
  push:
      branches:
        - dev
  pull_request:
        branches:
          - dev
env:
  PIPENV_PIPFILE: Docker/Pipfile

jobs:
  code_quality: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      
      - name: install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: |
          pipenv run pip install "setuptools==57.5.0"
          pipenv install --dev
          pipenv install pytest pytest-cov flake8 black safety
      
      - name: Code formatting check
        run: pipenv run black --check .

      - name: Flake lint
        run: |
          pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
