name: CI Workflow
on:
  push:
      branches:
        - dev
  pull_request:
        branches:
          - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: |
          export PIPENV_PIPFILE=Docker/Pipfile
          pipenv install --dev --ignore-pipfile
          pipenv install pytest pytest-cov flake8 black
      
      - name: Code formatting check
        run: pipenv run black --check .

      - name: Flake lint
        run: |
          pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
      - name: Debug Django
        run: |
          pipenv --venv
          pipenv graph

      - name: Django check
        run: pipenv run python Docker/manage.py check --deploy

      - name: Django tests
        run: |
          pipenv run python Docker/manage.py collectstatic --noinput
          pipenv run pytest --cov=. --cov-report=xml --cov-report=html --junitxml=pytest.xml

