name: Deployment on AWS EKS
on:
  push:
      branches:
        - dev
  pull_request:
        branches:
          - dev
env:
  DOCKER_IMAGE: titouonee/clouddevops_ecommerce
  GITHUB_BRANCH: dev

jobs:
  deployment:
    name: deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout manifest repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name : Update image tag
        run: |
          cd kubernetes/manifests
          kustomize edit set image ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

      - name: Commit and push changes
        run: |
          git config --local user.email " secrets.GITHUB_EMAIL"
          git config --local user.name "titouonee"
          git add kubernetes/manifests
          git diff --staged --quiet || git commit -m "Update image tag: sha-${{ github.sha }}"
          git push origin ${{ env.GITHUB_BRANCH }}