name: Update of manifests
on:
  workflow_run: 
    workflows: ["Push to DockerHub"]
    types: 
      - completed
env:
  DOCKER_IMAGE: titouonee/clouddevops_ecommerce

jobs:
  deployment:
    name: deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Kustomize and checkov
        run: |
          curl -sL "https://github.com/kubernetes-sigs/kustomize/releases/download/${KUSTOMIZE_VERSION}/kustomize_${KUSTOMIZE_VERSION#v}_linux_amd64.tar.gz" \
                | tar xz
          sudo mv kustomize /usr/local/bin/kustomize
          pip install checkov

      - name: Update image tag
        run: | 
          cd kubernetes/manifests
          kustomize edit set image ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
     
      - name: Scan with checkov
        run: |
          checkov --directory kubernetes/manifests gitops/ \
                  --framework kubernetes \
                  --output sarif --output-file checkov-results.sarif

      - name: Upload checkov report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov-manifests-results.sarif

      # no use of pull request for learning simplicity
      - name: Commit and push changes
        run: |
          git config --local user.email " secrets.GITHUB_EMAIL"
          git config --local user.name "titouonee"
          git add kubernetes/manifests
          git diff --staged --quiet || git commit -m "Update image tag: sha-${{ github.sha }}"
          git push origin master

#      - name: Create Pull Request for Manifests
#        uses: peter-evans/create-pull-request@v6
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          commit-message: 'feat(deployment): Update K8s image tag to sha-${{ github.sha }}'
#          title: 'CI/CD: New Image Tag ${{ github.sha }} Ready for Review'
#          body: 'Automatic manifest update triggered by successful image push. Please review.'
#          branch: 'ci-update-k8s-manifest-${{ github.sha }}'
#          base: 'master'