name: Deployment on AWS EKS
on:
  push:
      branches:
        - dev
  pull_request:
        branches:
          - dev
env:
  PIPENV_PIPFILE: Docker/Pipfile
  DOCKER_IMAGE: titouonee/clouddevops_ecommerce
  GITHUB_REPOSITORY: Titou-Onee/clouddevops_ecommerce
  GITHUB_BRANCH: dev
  K8S_CONFIG_REPO: ./kubernetes/manifests

jobs:
  deployment:
    name: deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout manifest repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.K8S_CONFIG_REPO }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./kubernetes/manifests

      - name : Update image tag
        run: |
          cd kubernetes/manifests
          NEW_TAG=$(echo "${{ needs.build.outputs.image-tag }}" | grep "latest" || echo "${{ needs.build.outputs.image-tag }}" | head -n1)
          sed -i "s|image: .*/django-ecommerce:.*|image: $NEW_TAG|g" deployment.yml
      
      - name: Commmit and push
        run: |
          cd kubernetes/manifests
          git config --local user.email "${{ secrets.GITHUB_MAIL}}"
          git config --local user.name "titou-onee"
          git add deployment.yml
          git commit -m "Update image to ${{ github.sha }}"
          git push origin ${{ env.GITHUB_BRANCH}}