name: Update of manifests
on:
  workflow_call:
    inputs:
      DEPLOY_TAG:
        description: 'tag of the deployed image'
        type: string
        required: true
      DOCKER_IMAGE:
        description: 'path of the docker image'
        type: string
        required: true

jobs:
  deployment:
    name: deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update image tag
        run: | 
          cd kubernetes/manifests
          kustomize edit set image ${{ inputs.DOCKER_IMAGE }}:${{ inputs.DEPLOY_TAG }}
 
      - name: Scan Kubernetes manifests with Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: |
            kubernetes/manifests
            gitops
          framework: kubernetes
          output_format: sarif
          output_file_path: checkov-results.sarif


      - name: Upload checkov report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov-results.sarif

      # no use of pull request for learning simplicity
      - name: Commit and push changes
        run: |
          git config --local user.email " secrets.GITHUB_EMAIL"
          git config --local user.name "titouonee"
          git add kubernetes/manifests
          git diff --staged --quiet || git commit -m "Update image tag: sha-${{ inputs.DEPLOY_TAG }}"
          git push origin master

#      - name: Create Pull Request for Manifests
#        uses: peter-evans/create-pull-request@v6
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          commit-message: 'feat(deployment): Update K8s image tag to sha-${{ inputs.DEPLOY_TAG }}'
#          title: 'CI/CD: New Image Tag ${{ inputs.DEPLOY_TAG }} Ready for Review'
#          body: 'Automatic manifest update triggered by successful image push. Please review.'
#          branch: 'ci-update-k8s-manifest-${{ inputs.DEPLOY_TAG }}'
#          base: 'master'