name: update of manifests
on:
  workflow_run: 
    workflows: ["push on DockerHub"]
    types: 
      - completed
env:
  DOCKER_IMAGE: titouonee/clouddevops_ecommerce

jobs:
  deployment:
    name: deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name : Update image tag
        run: |
          cd kubernetes/manifests
          kustomize edit set image ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

      - name: Commit and push changes
        run: |
          git config --local user.email " secrets.GITHUB_EMAIL"
          git config --local user.name "titouonee"
          git add kubernetes/manifests
          git diff --staged --quiet || git commit -m "Update image tag: sha-${{ github.sha }}"
          git push origin master