name: Update of manifests
on:
  workflow_run: 
    workflows: ["Push to DockerHub"]
    types: 
      - completed
env:
  DOCKER_IMAGE: titouonee/clouddevops_ecommerce

jobs:
  deployment:
    name: deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Kustomize and checkov
        run: |
          curl -sL https://git.io/install-kustomize | bash
          sudo mv kustomize /usr/local/bin/
          pip install checkov

      - name: Update image tag
        run: | 
          cd kubernetes/manifests
          kustomize edit set image ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
     
      - name: Scan with checkov
        run: |
          checkov --directory kubernetes/manifests gitops/ \
                  --framework kubernetes \
                  --output sarif --output-file checkov-results.sarif

      - name: Upload checkov report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov-manifests-results.sarif
          
      - name: Commit and push changes
        run: |
          git config --local user.email " secrets.GITHUB_EMAIL"
          git config --local user.name "titouonee"
          git add kubernetes/manifests
          git diff --staged --quiet || git commit -m "Update image tag: sha-${{ github.sha }}"
          git push origin master