name: trivy

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read 
      security-events: write 
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/titou-onee/clouddevops_ecommerce:${{ github.sha }} ./Docker

      - name: Docker image test
        run: |
          docker compose up -d --build --name test-container \
            -p 8000:8000 docker.io/titou-onee/clouddevops_ecommerce:${{ github.sha }}
          sleep 30
          curl -f http://localhost:8000/home.html || exit 1
          docker stop test-container

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'docker.io/titou-onee/clouddevops_ecommerce:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
