name: Format Lint Code
on:
  push:
      branches:
        - master
        - dev
  pull_request:


jobs:
  code_quality: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Cache Pipenv environment
        uses: actions/cache@v4
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-
        

      - name: Install dependencies
        run: |
          pipenv run pip install "setuptools==57.5.0"
          pipenv install --dev --skip-lock
          pipenv install flake8 black

      - name: Code formatting check
        run: pipenv run black --check .
        # In  the context of this project, we can accept to continue on error 
        continue-on-error: true

      - name: Flake lint
        run: |
          pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
