name: Format Lint Code
on:
  workflow_call:
permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  plumber:
    name: plumber-ci
    runs-on: ubuntu-latest
    steps:
      - uses: getplumber/plumber@40bd6b5bb8ff4f0944feacaeb41dea6bce08d62d # pinned plumber version: v0.4.28
        with:
          score-push: true