name: Plumber-ci
on:  
    push:
        branches:
            - dev
            - master
        paths:
            - '.github/workflows/**'
permissions:
  contents: read
  security-events: write
  id-token: write
# Plumber control
jobs:
  plumber:
    name: plumber-ci
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: getplumber/plumber@40bd6b5bb8ff4f0944feacaeb41dea6bce08d62d # pinned plumber version: v0.4.28
        with:
          score-push: true
          github-token: ${ secret.PLUMBER_TOKEN }
