name: Push to DockerHub
on:
  workflow_run: 
    workflows: ["Security checks"]
    types: 
      - completed
env:
  DOCKER_IMAGE: titouonee/clouddevops_ecommerce

jobs:
  push_image:
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifacts@v4
        with:
          name: signed-docker-image
          path: .

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Verify image integrity
        run: cosign verify-blob --key env://COSIGN_PUBLIC_KEY image.tar --signature image.tar.sig
        env:
          COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
      
      - name: Load docket image
        run: docker load -i image.tar

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Tag and push to DockerHub
        run: |
          docker tag ${{ env.DOCKER_IMAGE }}:ci-signed ${{ env.DOCKER_IMAGE }}:latest
          docker tag ${{ env.DOCKER_IMAGE }}:ci-signed ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          
          docker push ${{ env.DOCKER_IMAGE }}:latest
          docker push ${{ env.DOCKER_IMAGE }}:${{ github.sha }}