name: Push to DockerHub
on:
  workflow_call:
    inputs:
      RELEASE_TAG:
        description: 'Tag of the docker image'
        type: string
        required: true
      DEFAULT_SHA:
        description: 'sha of the commit'
        type: string
        required: true
      DOCKER_IMAGE:
        description: 'path of the docker image'
        type: string
        required: true
      RUN_ID:
        description: "run ID of the upload of the artifact"
        type: string
        required: true
    secrets:
      COSIGN_PUBLIC_KEY:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

permissions:
  actions: read
  contents: read

jobs:
  push_image:
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: signed-docker-image
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: inputs
          path: .

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Verify image integrity
        run: cosign verify-blob --key env://COSIGN_PUBLIC_KEY image.tar --signature image.tar.sig
        env:
          COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
      
      - name: Load docket image
        run: docker load -i image.tar

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Tag and push to DockerHub
        run: |
          docker tag ${{ inputs.DOCKER_IMAGE }}:ci-signed ${{ inputs.DOCKER_IMAGE }}:${{ inputs.image_tag }}
          docker tag ${{ inputs.DOCKER_IMAGE }}:ci-signed ${{ inputs.DOCKER_IMAGE }}:${{ inputs.sha }}
          
          docker push ${{ inputs.DOCKER_IMAGE }}:${{ inputs.image_tag }}
          docker push ${{ inputs.DOCKER_IMAGE }}:${{ inputs.sha }}


