name: push on DockerHub
on:
  push:
      branches:
        - dev
  pull_request:
        branches:
          - dev
env:
  PIPENV_PIPFILE: Docker/Pipfile
  DOCKER_IMAGE: titouonee/clouddevops_ecommerce

jobs:
  code_quality:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE }}:test ./Docker

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Tag and push to DockerHub
        run: |
          docker tag ${{ env.DOCKER_IMAGE }}:test ${{ env.DOCKER_IMAGE }}:latest
          docker tag ${{ env.DOCKER_IMAGE }}:test ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          
          docker push ${{ env.DOCKER_IMAGE }}:latest
          docker push ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

      - name: Cleanup local images
        if: always()
        run: |
          docker rmi ${{ env.DOCKER_IMAGE }}:test || true
          docker system prune -f || true

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: |
           trivy-fs-results.sarif
           trivy-image-results.sarif
           retention-days: 30