name: Security checks
on:
  workflow_run: 
    workflows: ["Format Lint Code"]
    types: 
      - completed
env:
  DOCKER_IMAGE: titouonee/clouddevops_ecommerce

jobs:
  security_checks:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name : Restore Pipenv environment
        uses: actions/cache@v4
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
 
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   
        with:
          args:
            -Dsonar.projectKey="Titou-Onee_CloudDevOps_ecommerce"
            -Dsonar.organization="titou-onee"
          projectBaseDir: .
          
      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml
          format: 'sarif'
          output: 'trivy-fs-results.sarif'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }}:ci-signed ./Docker


      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: '${{ env.DOCKER_IMAGE }}:ci-signed'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-image-results.sarif'
          severity: 'CRITICAL,HIGH'
      
      - name: Save Docker image
        run: docker save ${{ env.DOCKER_IMAGE }}:ci-signed -o image.tar

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign with Cosign
        run: |
          cosign sign-blob --key-env env://COSIGN_PRIVATE_KEY image.tar > image.tar.sig
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: Upload image as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: signed-docker-image
          path: |
            image.tar
            image.tar.sig
          retention-days: 1

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: safety-report
          path: |
            safety-report.json
            trivy-image-results.sarif
            trivy-fs-results.sarif
          retention-days: 1

